name: mcp-issue-orchestrator
description: "Publish epics/stories to GitHub, decompose stories into task issues, and offload tasks via MCP."
author: "Custom"

# Config sources
bmm_config: "{project-root}/_bmad/bmm/config.yaml"
bmcp_config: "{project-root}/_bmad/bmcp/config.yaml"

user_name: "{bmm_config}:user_name"
communication_language: "{bmm_config}:communication_language"
planning_artifacts: "{bmm_config}:planning_artifacts"
implementation_artifacts: "{bmm_config}:implementation_artifacts"
date: system-generated

github_repo: "{bmcp_config}:github_repo"
github_project_number: "{bmcp_config}:github_project_number"
issue_label_prefix: "{bmcp_config}:issue_label_prefix"
offload_provider: "{bmcp_config}:offload_provider"

# Workflow components
installed_path: "{project-root}/_bmad/bmcp/workflows/mcp-issue-orchestrator"
instructions: "{installed_path}/instructions.md"

variables:
  epics_location: "{planning_artifacts}"
  epics_pattern: "*epic*.md"
  epic_file: "{planning_artifacts}/epics.md"
  story_filter: "" # Optional: epic/story key or title filter
  dry_run: "false" # If true, do not call MCP tools
  story_plans_dir: "{implementation_artifacts}/story-plans"

input_file_patterns:
  epics:
    description: "Epics with user stories"
    whole: "{planning_artifacts}/*epic*.md"
    sharded: "{planning_artifacts}/*epic*/*.md"
    load_strategy: "FULL_LOAD"
  story_plans:
    description: "Story implementation plans (generated by SM planning workflow)"
    whole: "{implementation_artifacts}/story-plans/*.md"
    sharded: "{implementation_artifacts}/story-plans/*/*.md"
    load_strategy: "SELECTIVE_LOAD"

default_output_file: "{implementation_artifacts}/github-issue-map.md"

standalone: true
web_bundle: false
